### ISSUE TITLE
Please add License

### ISSUE THREAD

**Issue by LandonTClipp** [luca-s/mpi-master-slave#1]
Hello! I was wanting to fork your repo for some work that I need to do, however I do not find any license that would allow me to extend your work. Would you consider adding an open license so I may do this? Also have you considered adding this to PyPi? I think it would be very useful. Thanks!

**Comment by luca-s** [comment]
Done! ;) I didn't really thought of making a proper module, I expected people to copy/paste the code in their project...but pull requests are always welcome.

**Comment by LandonTClipp** [comment]
Thanks! I will end up forking this. I'll be sure to contribute back with a pull request if I make any substantial changes.
