### ISSUE TITLE
PyPi?

### ISSUE THREAD

**Issue by LandonTClipp** [luca-s/mpi-master-slave#3]
Hi Luca-s!

I wanted to bring up again if you were interested in publishing this on PyPi. I can do this work if you'd like. It would be useful to have it there. Let me know your thoughts. Thanks!

**Comment by luca-s** [comment]
Sounds good to me! I am more than happy if you like to do that. Thanks

**Comment by LandonTClipp** [comment]
Great, it is now on PyPi as mpi-master-slave under release 0.1.0.
