### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by wjmadison** [luca-s/mpi-master-slave#9]
Hi Luca, I'm trying to run this for an example on master-slave architecture. Every time, rather than behaving as shown, all examples lead to an infinite loop, where the first line (name, rank and total) print, and nothing else, as it appears to get stuck in the !work_queue.done while loop. I read through the tutorial and it mentions extending the do_work method and implementing the master class. The master class is already implemented and do_work is already implemented in the MySlave class. Is there something specific I have to do to get it working or this a problem with the code?

**Comment by luca-s** [comment]
I believe the issue is in your code. I just tested the first example in the tutorial and it works fine.

Could you please try the example code as in the tutorial, without changes, and see if it runs properly?

**Comment by luca-s** [comment]
by the way, I tested with mpi4py==4.0.0

**Comment by wjmadison** [comment]
Running it exactly as it is from the repo gives me an error from mpi_master_slave not being found, so I drag example1 out of the examples folder, to the master folder, then it doesn't give me an error, it just starts, goes to "I am [my computer name] rank 0 (total 1)", then infinitely loops in the "while not self.work_queue.done():" starting on line 40. When it didn't work, I copy and pasted the version of example1 that appears in the tutorial into example1.py to see if that would fix it, still to no avail.

My mpi4py is also 4.0.0

BTW. thanks for the quick response

**Comment by luca-s** [comment]
So it looks like an issue on your machine.  Are you running Linux?

This is how it runs on my machine:

```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install mpi4py
Collecting mpi4py
  Using cached mpi4py-4.0.0-cp310-cp310-linux_x86_64.whl
Installing collected packages: mpi4py
Successfully installed mpi4py-4.0.0
$ git clone https://github.com/luca-s/mpi-master-slave.git
$ cd mpi-master-slave/
$ mv examples/example1.py .
$ mpiexec -n 4 python example1.py
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
I am  myhost rank 2 (total 4)
I am  myhost rank 1 (total 4)
I am  myhost rank 0 (total 4)
I am  myhost rank 3 (total 4)
  Slave myhost rank 2 executing "Do task" task_id "0"
  Slave myhost rank 3 executing "Do task" task_id "1"
Master: slave finished is task and says "I completed my task (0)"
Master: slave finished is task and says "I completed my task (1)"
  Slave myhost rank 1 executing "Do task" task_id "2"
  Slave myhost rank 3 executing "Do task" task_id "4"
  Slave myhost rank 2 executing "Do task" task_id "3"
Master: slave finished is task and says "I completed my task (2)"
Master: slave finished is task and says "I completed my task (4)"
  Slave myhost rank 3 executing "Do task" task_id "6"
  Slave myhost rank 1 executing "Do task" task_id "5"
Master: slave finished is task and says "I completed my task (3)"
  Slave myhost rank 2 executing "Do task" task_id "7"
Master: slave finished is task and says "I completed my task (6)"
  Slave myhost rank 3 executing "Do task" task_id "8"
Master: slave finished is task and says "I completed my task (5)"
Master: slave finished is task and says "I completed my task (7)"
Master: slave finished is task and says "I completed my task (8)"
  Slave myhost rank 1 executing "Do task" task_id "9"
Master: slave finished is task and says "I completed my task (9)"
Task completed (rank 3)
Task completed (rank 0)
Task completed (rank 2)
Task completed (rank 1)
```

**Comment by wjmadison** [comment]
I was running with "python example1.py", not mpiexec. Now it works, but mine does the tasks in a different order. I ran it with the exact same command "mpiexec -n 4 python example1.py"
I am  [my pc name] rank 1 (total 4)
  Slave [my pc name] rank 1 executing "Do task" task_id "1"
  Slave [my pc name] rank 1 executing "Do task" task_id "3"
  Slave [my pc name] rank 1 executing "Do task" task_id "6"
  Slave [my pc name] rank 1 executing "Do task" task_id "9"
Task completed (rank 1)
I am  [my pc name] rank 3 (total 4)
  Slave [my pc name] rank 3 executing "Do task" task_id "0"
  Slave [my pc name] rank 3 executing "Do task" task_id "4"
  Slave [my pc name] rank 3 executing "Do task" task_id "7"
Task completed (rank 3)
I am  [my pc name] rank 2 (total 4)
  Slave [my pc name] rank 2 executing "Do task" task_id "2"
  Slave [my pc name] rank 2 executing "Do task" task_id "5"
  Slave [my pc name] rank 2 executing "Do task" task_id "8"
Task completed (rank 2)
I am  [my pc name] rank 0 (total 4)
Master: slave finished is task and says "I completed my task (1)"
Master: slave finished is task and says "I completed my task (0)"
Master: slave finished is task and says "I completed my task (2)"
Master: slave finished is task and says "I completed my task (3)"
Master: slave finished is task and says "I completed my task (4)"
Master: slave finished is task and says "I completed my task (5)"
Master: slave finished is task and says "I completed my task (6)"
Master: slave finished is task and says "I completed my task (7)"
Master: slave finished is task and says "I completed my task (8)"
Master: slave finished is task and says "I completed my task (9)"
Task completed (rank 0)

**Comment by luca-s** [comment]
That's to be expected in concurrent programming, you cannot predict the order in which each subprocess is executed.
